env:
  commonjs: true
  es6: true
  node: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  semi:
    - error
    - never
  no-console:
    - error
    - allow:
        - info
        - warn
        - error
  consistent-return: 0
